workflows:
  android-workflow:
    name: Naweri Beast Dynamic Generator
    max_build_duration: 10
    instance_type: mac_mini_m1
    scripts:
      - name: Generate JKS Keystore
        script: |
          # Use the filename provided by PHP
          keytool -genkeypair -v \
            -keystore $DYNAMIC_FILENAME \
            -alias "$KEY_ALIAS" \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEYSTORE_PASSWORD" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=$PUBLISHER_NAME, OU=$ORG_UNIT, O=$ORG_NAME, L=$CITY, S=$STATE, C=$COUNTRY" \
            -noprompt

      - name: Post File Back to PHP
        script: |
          # Send the file and its dynamic name back for DB storage
          curl -X POST $CALLBACK_URL \
            -F "keystore_file=@$DYNAMIC_FILENAME" \
            -F "dynamic_filename=$DYNAMIC_FILENAME" \
            -F "auth_token=$INTERNAL_TOKEN" \
            -F "db_id=$DB_RECORD_ID"
